folia-supported: false
name: ${pluginName}
version: ${version}
main: ru.oftendev.recipebook.RecipeBookPlugin
api-version: 1.21.8
authors: [ _OfTeN_, joogiebear ]
depend:
  - eco
softdepend:
  - EcoShop
  - VaultPack
  - libreforge
permissions:
  recipebook.admin.create:
    description: Open the in-game recipe creator GUI
    default: op
  recipebook.admin:
    description: Admin commands (unlock/lock recipes)
    default: op

commands:
  recipebook:
    description: Base Command
    permission: recipebook.command.recipebook
    aliases: [ rbook ]
