folia-supported: false
name: ${pluginName}
version: ${version}
main: io.auxilor.ecocrafting.EcoCraftingPlugin
api-version: 1.21.8
authors: [Exanthiax, _OfTeN_, joogiebear, Auxilor ]
depend:
  - eco
softdepend:
  - EcoShop
  - libreforge
permissions:
  ecocrafting.admin.create:
    description: Open the in-game recipe creator GUI
    default: op
  ecocrafting.admin:
    description: Admin commands (unlock/lock recipes)
    default: op

commands:
  ecocrafting:
    description: Base Command
    permission: ecocrafting.command.ecocrafting
    aliases: [ rbook ]
