folia-supported: false
name: ${pluginName}
version: ${version}
main: ru.oftendev.recipebook.RecipeBookPlugin
api-version: 1.21.8
authors: [ _OfTeN_, joogiebear ]
depend:
  - eco
softdepend:
  - EcoShop
  - VaultPack
  - libreforge
commands:
  recipebook:
    description: Base Command
    permission: recipebook.command.recipebook
    aliases: [ rbook ]
